spring:
  config:
    activate:
      on-profile: local

  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

logging:
  level:
    org:
      springframework:
        jdbc:
          core: TRACE
